### ISSUE TITLE
OOm

### ISSUE THREAD

**Issue by johnlint** [allure-framework/allure-bamboo#211]
For some of our bamboo builds, allure is throwing a report about memory but there seems to be plenty of memory on the bamboo box / allocated to bamboo.  This is only happening for some of the reports.
`
Something went wrong with Allure Report generation. Here are some details: 
java.lang.RuntimeException: Failed to generate allure report
	at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:40)
	at io.qameta.allure.bamboo.AllureBuildCompleteAction.execute(AllureBuildCompleteAction.java:104)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$chainCompleted$2(ChainPluginSupportImpl.java:139)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:97)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:93)
	at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:53)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.callActionFunction(ChainPluginSupportImpl.java:93)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$withCustomVariableContext$0(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:107)
	at com.atlassian.bamboo.variable.CustomVariableContextRunnerImpl.execute(CustomVariableContextRunnerImpl.java:31)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.withCustomVariableContext(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.chainCompleted(ChainPluginSupportImpl.java:135)
	at sun.reflect.GeneratedMethodAccessor2809.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.orm.hibernate5.support.OpenSessionInterceptor.invoke(OpenSessionInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy254.chainCompleted(Unknown Source)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.finaliseChainStateIfChainExecutionHasCompleted(ChainExecutionManagerImpl.java:1131)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1700(ChainExecutionManagerImpl.java:135)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$3.run(ChainExecutionManagerImpl.java:678)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.execute(ChainExecutionManagerImpl.java:593)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1300(ChainExecutionManagerImpl.java:135)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2$1.run(ChainExecutionManagerImpl.java:447)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2.run(ChainExecutionManagerImpl.java:432)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.onBuildFinished(ChainExecutionManagerImpl.java:418)
	at sun.reflect.GeneratedMethodAccessor1011.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:42)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.lambda$null$0(AsynchronousAbleEventDispatcher.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.buildobjects.process.ExternalProcessFailureException: External process '/bin/bash /tmp/allure/2.13.6/binary/bin/allure generate -o /opt/atlassian/bamboo/temp/1619580421785-1/report /opt/atlassian/bamboo/temp/1619580421785-0/f43e6d50-d7a8-43c0-a99b-f2cbcdfd53a3' returned 1 after 90ms
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005c0000000, 8589934592, 0) failed; error='Cannot allocate memory' (errno=12)

	at org.buildobjects.process.Proc.<init>(Proc.java:108)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:193)
	at io.qameta.allure.bamboo.AllureCommandLineSupport.runCommand(AllureCommandLineSupport.java:22)
	at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:33)
	... 44 more
`

**Comment by vbragin** [comment]
Bamboo uses the external execution to generate a report:
https://github.com/allure-framework/allure2
Maybe you can ask there what is the minimum parameters it required, and configure your system according requirements.
