### ISSUE TITLE
Allure Bamboo compatibility with Bamboo 8.0.3

### ISSUE THREAD

**Issue by tskorupka** [allure-framework/allure-bamboo#251]
Hi, I think it is unable to get Allure plugin to work with bamboo 8.0.3,

Took a shot to compile it under bamboo 8.0.3 dependencies, aligned with newest sdk,

What should we do next?

#252 

Cheers

**Comment by EHarunAVST** [comment]
Hi, yeah I also having an issue recently with Bamboo 8.1.8 version. The issue log was as following
{code}
Something went wrong with Allure Report generation. Here are some details: 
java.lang.RuntimeException: Failed to find Allure executable by name allure-2.7.0
	at io.qameta.allure.bamboo.AllureBuildCompleteAction.lambda$execute$1(AllureBuildCompleteAction.java:93)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at io.qameta.allure.bamboo.AllureBuildCompleteAction.execute(AllureBuildCompleteAction.java:92)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$chainCompleted$2(ChainPluginSupportImpl.java:139)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:97)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.call(ChainPluginSupportImpl.java:93)
	at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:55)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.callActionFunction(ChainPluginSupportImpl.java:93)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.lambda$withCustomVariableContext$0(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:107)
	at com.atlassian.bamboo.variable.CustomVariableContextRunnerImpl.execute(CustomVariableContextRunnerImpl.java:31)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.withCustomVariableContext(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.chainCompleted(ChainPluginSupportImpl.java:135)
	at sun.reflect.GeneratedMethodAccessor2914.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.orm.hibernate5.support.OpenSessionInterceptor.invoke(OpenSessionInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy279.chainCompleted(Unknown Source)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.finaliseChainStateIfChainExecutionHasCompleted(ChainExecutionManagerImpl.java:1152)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1700(ChainExecutionManagerImpl.java:137)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$3.run(ChainExecutionManagerImpl.java:695)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.execute(ChainExecutionManagerImpl.java:610)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1300(ChainExecutionManagerImpl.java:137)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2$1.run(ChainExecutionManagerImpl.java:464)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2.run(ChainExecutionManagerImpl.java:449)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.onBuildFinished(ChainExecutionManagerImpl.java:435)
	at sun.reflect.GeneratedMethodAccessor581.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:42)
	at com.atlassian.event.internal.ComparableListenerInvoker.invoke(ComparableListenerInvoker.java:48)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.lambda$null$0(AsynchronousAbleEventDispatcher.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:48)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
	at java.lang.Thread.run(Thread.java:750)
{code}

**Comment by vbragin** [comment]
Try to use the last version
