### ISSUE TITLE
 java.lang.RuntimeException: Failed to generate allure report w/ Allure-Bamboo 2.5.0

### ISSUE THREAD

**Issue by Edge-Man** [allure-framework/allure-bamboo#51]
Hello, 

I am getting this error when using the Allure Bamboo plugin which is currently published to the Atlasssian portal. I have followed the directions and it seems that the error is related to the report generator not able to parse the dates? 

Running the Report Generator locally does not show an issue. 

Log: 
`java.lang.RuntimeException: Failed to generate allure report
	at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:40)
	at io.qameta.allure.bamboo.AllureBuildCompleteAction.execute(AllureBuildCompleteAction.java:104)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$4.call(ChainPluginSupportImpl.java:140)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$4.call(ChainPluginSupportImpl.java:137)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$2.call(ChainPluginSupportImpl.java:102)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$2.call(ChainPluginSupportImpl.java:98)
	at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:53)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.callActionFunction(ChainPluginSupportImpl.java:98)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.access$000(ChainPluginSupportImpl.java:45)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl$1.run(ChainPluginSupportImpl.java:88)
	at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:174)
	at com.atlassian.bamboo.variable.CustomVariableContextRunnerImpl.execute(CustomVariableContextRunnerImpl.java:31)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.withCustomVariableContext(ChainPluginSupportImpl.java:85)
	at com.atlassian.bamboo.chains.ChainPluginSupportImpl.chainCompleted(ChainPluginSupportImpl.java:137)
	at sun.reflect.GeneratedMethodAccessor2673.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.orm.hibernate5.support.OpenSessionInterceptor.invoke(OpenSessionInterceptor.java:84)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy234.chainCompleted(Unknown Source)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.finaliseChainStateIfChainExecutionHasCompleted(ChainExecutionManagerImpl.java:1099)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1700(ChainExecutionManagerImpl.java:127)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$4.run(ChainExecutionManagerImpl.java:661)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.execute(ChainExecutionManagerImpl.java:581)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.access$1300(ChainExecutionManagerImpl.java:127)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2$1.run(ChainExecutionManagerImpl.java:441)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl$2.run(ChainExecutionManagerImpl.java:426)
	at io.atlassian.util.concurrent.ManagedLocks$ManagedLockImpl.withLock(ManagedLocks.java:302)
	at com.atlassian.bamboo.chains.ChainExecutionManagerImpl.onBuildFinished(ChainExecutionManagerImpl.java:412)
	at sun.reflect.GeneratedMethodAccessor2339.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:36)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:47)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
	at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:17)
	at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:41)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.buildobjects.process.ExternalProcessFailureException: External process '/bin/bash /tmp/allure/2.5.0/binary/bin/allure generate -o /opt/j2ee/domains/*****/bamboo/current/temp/1535479793952-1/report /opt/j2ee/domains/*****/bamboo/current/temp/1535479793952-0/42aab9a4-da66-4236-aaaa-e581f8dfdb90' returned 1 after 1038ms
**Exception in thread "main" java.time.format.DateTimeParseException: Text '28 Aug 2018 18:09:52 GMT' could not be parsed at index 0**
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at java.time.LocalDateTime.parse(LocalDateTime.java:492)
	at java.time.LocalDateTime.parse(LocalDateTime.java:477)
	at io.qameta.allure.junitxml.JunitXmlPlugin.getUnix(JunitXmlPlugin.java:134)
	at io.qameta.allure.junitxml.JunitXmlPlugin.parseTestSuite(JunitXmlPlugin.java:124)
	at io.qameta.allure.junitxml.JunitXmlPlugin.parseRootElement(JunitXmlPlugin.java:101)
	at io.qameta.allure.junitxml.JunitXmlPlugin.lambda$readResults$0(JunitXmlPlugin.java:87)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.qameta.allure.junitxml.JunitXmlPlugin.readResults(JunitXmlPlugin.java:87)
	at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:32)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:32)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:54)
	at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:43)
	at io.qameta.allure.Commands.generate(Commands.java:89)
	at io.qameta.allure.CommandLine.run(CommandLine.java:129)
	at java.util.Optional.orElseGet(Optional.java:267)
	at io.qameta.allure.CommandLine.main(CommandLine.java:72)

	at org.buildobjects.process.Proc.<init>(Proc.java:108)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:193)
	at io.qameta.allure.bamboo.AllureCommandLineSupport.runCommand(AllureCommandLineSupport.java:22)
	at io.qameta.allure.bamboo.AllureExecutable.generate(AllureExecutable.java:33)
	... 46 more`

**Comment by ksenia-loseva** [comment]
Any info about this? I got this same exception after changing some things in my tests.

**Comment by ksenia-loseva** [comment]
To solve this problem, I created a new plan in Bamboo from scratch and configured it the same way the old plan was configured. The new plan generates Allure Reports correctly. However, I don't know the root cause of the problem.
