### ISSUE TITLE
ALLURE REPORT UNKNOWN for published artifact

### ISSUE THREAD

**Issue by ifn** [allure-framework/allure-bamboo#80]
Bamboo job produces xml report and Bamboo shows tests under its Tests tab but **allure report reveals no tests**.
There is `Finished publishing of artifact Non required job artifact: [Allure Report], pattern: [**] anchored at: [export/allure_results] in 458.6 ms` record in log.
Reports were shown before but broke for unknown reason. And there are no errors in job. What should I do to investigate the problem?

**Comment by smecsia** [comment]
Hi @ifn, Does the `Allure` tab show up in the build result? If so, what does it say? Another way to investigate would be checking the Bamboo server logs during the build completion to see if there's anything interesting happening there. 
Could you also provide the version of Allure, Allure Bamboo, Bamboo itself?

**Comment by ifn** [comment]
Hi @smecsia. Thanks for reply.

Job log:
```
20-Sep-2019 13:20:00	Publishing an artifact: Allure Report
20-Sep-2019 13:20:08	Finished publishing of artifact Non required job artifact: [Allure Report], pattern: [**] anchored at: [export/allure_results] in 7.453 s

```
Server log with some extracts:
```
2019-09-20 13:20:00,770 INFO [18-BAM::Local Agent 1::Agent:pool-33-thread-1] [AbstractArtifactManager] Publishing [Allure Report] for SCCTESTS-SUBMITTER-PLOV-235: 5180 file(s) matching [**] in directory /data/bamboo/data/xml-data/build-dir/SCCTESTS-SUBMITTER-PLOV/export/allure_results
2019-09-20 13:20:00,771 INFO [18-BAM::Local Agent 1::Agent:pool-33-thread-1] [AbstractArtifactManager] Trying to publish the artifact with handler: com.atlassian.bamboo.build.artifact.ServerLocalArtifactHandler
2019-09-20 13:20:08,196 INFO [18-BAM::Local Agent 1::Agent:pool-33-thread-1] [AbstractArtifactManager] Handler com.atlassian.bamboo.build.artifact.ServerLocalArtifactHandler published the artifact, size: 6 MB, time elapsed: 7.425 s
2019-09-20 13:20:08,281 INFO [18-BAM::Local Agent 1::Agent:pool-33-thread-1] [ExecuteBuildTask] Successfully removed working directory at '/data/bamboo/data/xml-data/build-dir/SCCTESTS-SUBMITTER-PLOV' for plan 'SCCTESTS-SUBMITTER-PLOV'

```


```
2019-09-20 13:20:08,485 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureBuildCompleteAction] Allure Report is enabled for SCC TESTS - scc-plo-submitter tests (test)
2019-09-20 13:20:08,485 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureBuildCompleteAction] Trying to get executable by name allure-2.5.0 for SCC TESTS - scc-plo-submitter tests (test)
2019-09-20 13:20:08,488 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureBuildCompleteAction] Starting artifacts downloading into /tmp/bamboo/1568985608481-0 for SCC TESTS - scc-plo-submitter tests (test)
2019-09-20 13:20:08,488 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureArtifactsManager] Found 1 artifacts totally for the build SCCTESTS-SUBMITTER-235
2019-09-20 13:20:08,488 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureArtifactsManager] artifact Allure Report matches the configured artifact name  for the build SCCTESTS-SUBMITTER-235
2019-09-20 13:20:08,641 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureArtifactsManager] Found 0 artifacts totally for the build SCCTESTS-SUBMITTER-235
2019-09-20 13:20:08,641 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureArtifactsManager] Found 0 artifacts totally for the build SCCTESTS-SUBMITTER-235
2019-09-20 13:20:08,641 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureBuildCompleteAction] Starting allure generate into /tmp/bamboo/1568985608482-0/report for SCC TESTS - scc-plo-submitter tests (test)
2019-09-20 13:20:10,349 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureExecutable] Report successfully generated to /tmp/bamboo/1568985608482-0/report
2019-09-20 13:20:10,349 INFO [AtlassianEvent::0-BAM::EVENTS:pool-1-thread-11] [AllureBuildCompleteAction] Allure has been generated successfully for SCC TESTS - scc-plo-submitter tests (test)
```



Allure Report tab:
Report with ALLURE REPORT UNKNOWN title and 0 cases.

Version:
Allure plugin: 1.10.0
Allure binary: 2.5.0
Bamboo: 6.9.2 build 60911 - 04 Jul 19

**Comment by smecsia** [comment]
Thank you for the details. It looks like everything was successful, but the report generation did not produce any results. Could you try to download artifacts from the build result and manually generate the report using Allure CLI? 
If the result would be the same, then it's something to ask about in the main allure project.

**Comment by ifn** [comment]
I downloaded allure results from bamboo and invoked with `allure serve` command - report is generated. There is no any in bamboo though.

**Comment by ifn** [comment]
Sometimes if I refresh the tab with allure report I get this `Unknown error has occurred during Allure Build. Please refer the server logs for details.` In logs (not sure that it is relevant):

```
2019-09-23 12:42:25,175 ERROR [http-nio-8085-exec-17] [runtime] Error executing FreeMarker template
FreeMarker template error:
Java method "com.atlassian.bamboo.ww2.FreemarkerContext.getWebPanels(String, Map)" threw an exception when invoked on com.atlassian.bamboo.ww2.FreemarkerContext object "com.atlassian.bamboo.ww2.FreemarkerContext@1d266a7c"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #list ctx.getWebPanels(location, para...  [in template "freemarker-lib/ui.ftl" in macro "renderWebPanels" at line 772, column 5]
        - Reached through: @ui.renderWebPanels location="plan.he...  [in template "decorators/planDecorator.ftl" at line 36, column 9]
----

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:285)
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:261)
        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:67)
        at freemarker.core.MethodCall._eval(MethodCall.java:76)
        at freemarker.core.Expression.eval(Expression.java:81)
        at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:72)
        at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
        at freemarker.core.Environment.visit(Environment.java:362)
        at freemarker.core.Environment.invoke(Environment.java:714)
        at freemarker.core.UnifiedCall.accept(UnifiedCall.java:86)
        at freemarker.core.Environment.visit(Environment.java:362)
        at freemarker.core.Environment.visitAndTransform(Environment.java:460)
        at freemarker.core.BlockAssignment.accept(BlockAssignment.java:55)
        at freemarker.core.Environment.visit(Environment.java:326)
        at freemarker.core.Environment.visit(Environment.java:332)
        at freemarker.core.Environment.visit(Environment.java:332)
        at freemarker.core.Environment.process(Environment.java:305)
        at freemarker.template.Template.process(Template.java:384)
        at com.atlassian.bamboo.ww2.FreemarkerRequestDispatcherPageFilter.applyDecorator(FreemarkerRequestDispatcherPageFilter.java:123)
        at org.apache.struts2.sitemesh.TemplatePageFilter.applyDecorator(TemplatePageFilter.java:116)
        at com.atlassian.bamboo.ww2.FreemarkerRequestDispatcherPageFilter.access$200(FreemarkerRequestDispatcherPageFilter.java:46)
        at com.atlassian.bamboo.ww2.FreemarkerRequestDispatcherPageFilter$BambooSitemeshDecorator.render(FreemarkerRequestDispatcherPageFilter.java:245)
        at com.opensymphony.sitemesh.webapp.decorator.BaseWebAppDecorator.render(BaseWebAppDecorator.java:33)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:84)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.filter.SessionCreationForAnonymousUserFilter.doFilter(SessionCreationForAnonymousUserFilter.java:40)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.filter.NewRelicTransactionNamingFilter.doFilter(NewRelicTransactionNamingFilter.java:30)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.ww2.StrutsPrepareFilter$1.doFilter(StrutsPrepareFilter.java:72)
        at org.apache.struts2.dispatcher.filter.StrutsPrepareFilter.doFilter(StrutsPrepareFilter.java:92)
        at com.atlassian.bamboo.ww2.StrutsPrepareFilter.handleRequest(StrutsPrepareFilter.java:46)
        at com.atlassian.bamboo.ww2.StrutsPrepareFilter.doFilter(StrutsPrepareFilter.java:38)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.filter.BambooProfilingFilter.doFilter(BambooProfilingFilter.java:72)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter$1.doFilter(DelegatingPluginFilter.java:58)
        at com.atlassian.prettyurls.filter.PrettyUrlsCombinedMatchDispatcherFilter.doFilter(PrettyUrlsCombinedMatchDispatcherFilter.java:56)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:70)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.filter.AccessLogFilter.doFilter(AccessLogFilter.java:84)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:265)
        at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
        at com.atlassian.bamboo.filter.SeraphLoginFilter$1.run(SeraphLoginFilter.java:61)
        at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:26)
        at com.atlassian.bamboo.security.ImpersonationHelper.runAs(ImpersonationHelper.java:54)
        at com.atlassian.bamboo.filter.SeraphLoginFilter.doFilter(SeraphLoginFilter.java:66)
        at org.acegisecurity.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:275)
        at org.acegisecurity.util.FilterChainProxy.doFilter(FilterChainProxy.java:149)
        at org.acegisecurity.util.FilterToBeanProxy.doFilter(FilterToBeanProxy.java:98)
        at com.atlassian.bamboo.filter.BambooAcegiProxyFilter.doFilter(BambooAcegiProxyFilter.java:21)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.filter.LicenseFilter.doFilter(LicenseFilter.java:74)
        at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.johnson.filters.AbstractJohnsonFilter.doFilter(AbstractJohnsonFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.seraph.filter.SecurityFilter.doFilter(SecurityFilter.java:242)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.seraph.filter.BaseLoginFilter.doFilter(BaseLoginFilter.java:148)
        at com.atlassian.seraph.filter.BambooLoginFilter.doFilter(BambooLoginFilter.java:37)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter$1.doFilter(DelegatingPluginFilter.java:58)
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter$1.doFilter(DelegatingPluginFilter.java:58)
        at com.atlassian.prettyurls.filter.PrettyUrlsCombinedMatchDispatcherFilter.doFilter(PrettyUrlsCombinedMatchDispatcherFilter.java:56)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:70)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.orm.hibernate5.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:152)
        at com.atlassian.bamboo.persistence.BambooSessionInViewFilter.doFilterInternal(BambooSessionInViewFilter.java:24)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:304)
        at com.atlassian.bamboo.filter.BambooCompressingFilter.doFilter(BambooCompressingFilter.java:37)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.filter.RequestCacheThreadLocalFilter.doFilter(RequestCacheThreadLocalFilter.java:40)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.filter.ClickjackingAndMimeTypeSniffingPreventionFilter.doFilter(ClickjackingAndMimeTypeSniffingPreventionFilter.java:36)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.bamboo.filter.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:49)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.core.filters.HeaderSanitisingFilter.doFilter(HeaderSanitisingFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter$1.doFilter(DelegatingPluginFilter.java:58)
        at com.atlassian.prettyurls.filter.PrettyUrlsCombinedMatchDispatcherFilter.doFilter(PrettyUrlsCombinedMatchDispatcherFilter.java:56)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:70)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
        at com.atlassian.bamboo.filter.UrlRewriteFilter.forwardTo(UrlRewriteFilter.java:314)
        at com.atlassian.bamboo.filter.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:199)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.core.filters.HeaderSanitisingFilter.doFilter(HeaderSanitisingFilter.java:44)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:39)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter$1.doFilter(DelegatingPluginFilter.java:58)
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter$1.doFilter(DelegatingPluginFilter.java:58)
        at com.atlassian.prettyurls.filter.PrettyUrlsCombinedMatchDispatcherFilter.doFilter(PrettyUrlsCombinedMatchDispatcherFilter.java:56)
        at com.atlassian.plugin.servlet.filter.DelegatingPluginFilter.doFilter(DelegatingPluginFilter.java:64)
        at com.atlassian.plugin.servlet.filter.IteratingFilterChain.doFilter(IteratingFilterChain.java:37)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:70)
        at com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter.doFilter(ServletFilterModuleContainerFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:679)
        at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: This stage is not a DB object
        at com.atlassian.bamboo.chains.cache.ImmutableChainStageImpl.getId(ImmutableChainStageImpl.java:132)
        at com.edwardawebb.bamboo.flow.impl.AbstractBambooFlowContextProvider$BuildDeployFlowSummary.addTriggeredDeploymentsResultingFrom(AbstractBambooFlowContextProvider.java:211)
        at com.edwardawebb.bamboo.flow.impl.AbstractBambooFlowContextProvider$BuildDeployFlowSummary.buildFlowForAllDefinedStagesAndEnvironments(AbstractBambooFlowContextProvider.java:174)
        at com.edwardawebb.bamboo.flow.impl.AbstractBambooFlowContextProvider$BuildDeployFlowSummary.buildFlowAsArray(AbstractBambooFlowContextProvider.java:118)
        at com.edwardawebb.bamboo.flow.impl.AbstractBambooFlowContextProvider.lambda$getContextMap$5(AbstractBambooFlowContextProvider.java:70)
        at com.edwardawebb.bamboo.flow.impl.AbstractBambooFlowContextProvider.timing(AbstractBambooFlowContextProvider.java:277)
        at com.edwardawebb.bamboo.flow.impl.AbstractBambooFlowContextProvider.getContextMap(AbstractBambooFlowContextProvider.java:70)
        at com.atlassian.plugin.web.descriptors.DefaultWebPanelModuleDescriptor$ContextAwareWebPanel.getHtml(DefaultWebPanelModuleDescriptor.java:144)
        at com.atlassian.bamboo.ww2.FreemarkerContext.renderWebPanel(FreemarkerContext.java:664)
        at com.atlassian.bamboo.ww2.FreemarkerContext.lambda$getWebPanels$4(FreemarkerContext.java:657)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.atlassian.bamboo.ww2.FreemarkerContext.getWebPanels(FreemarkerContext.java:658)
        at sun.reflect.GeneratedMethodAccessor8638.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1459)
        at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:56)
        at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:51)
        at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:63)
        ... 168 more
```

**Comment by ifn** [comment]
Do you have any suggestions? Can it be related with bamboo database?

**Comment by ifn** [comment]
Allure binary update to 2.7.0 solved the issue. I don't know what caused the problem. Maybe configuration error.
